INSERT INTO OAUTH_CLIENT_DETAILS(CLIENT_ID, RESOURCE_IDS, CLIENT_SECRET, SCOPE, AUTHORIZED_GRANT_TYPES, AUTHORITIES, ACCESS_TOKEN_VALIDITY, REFRESH_TOKEN_VALIDITY) VALUES ('private-client', 'csms', /*private-client1234*/'$2a$10$3aWZyoQHm4rnuBjBIjVeIOz8mdwynLJkSK93OMMKCAydCy0OFTHwW', 'private', 'password,authorization_code,refresh_token,implicit', 'USER', 10800, 2592000);
INSERT INTO OAUTH_CLIENT_DETAILS(CLIENT_ID, RESOURCE_IDS, CLIENT_SECRET, SCOPE, AUTHORIZED_GRANT_TYPES, AUTHORITIES, ACCESS_TOKEN_VALIDITY, REFRESH_TOKEN_VALIDITY) VALUES ('admin-client', 'csms', /*admin-client1234*/'$2a$10$m4CVi3SsiFJjqKxj5lktWuQ3lKUrDYMcZeQNEJhp5cNBvaL3FXOYq', 'private,admin', 'password,authorization_code,refresh_token,implicit', 'USER', 10800, 2592000);

INSERT INTO AUTHORITY(ID, NAME) VALUES (1, 'ADMIN');

INSERT INTO USER(ID, USER_NAME, PASSWORD, ACCOUNT_EXPIRED, ACCOUNT_LOCKED, CREDENTIALS_EXPIRED, ENABLED) VALUES (1, 'admin', /*admin1234*/'$2a$10$tJZ5OVwp4YW/GpsggpBtGe8PuIVWd2Yf1huJq.ZRZltl06djG4pVC', FALSE, FALSE, FALSE, TRUE);

INSERT INTO USERS_AUTHORITIES(USER_ID, AUTHORITY_ID) VALUES (1, 1);
