create table authority (id bigint generated by default as identity, name varchar(255), primary key (id));
create table user (id bigint generated by default as identity, account_expired boolean, account_locked boolean, credentials_expired boolean, enabled boolean, password varchar(255), user_name varchar(255), primary key (id));
create table users_authorities (user_id bigint not null, authority_id bigint not null);
alter table authority drop constraint if exists UKj9vkma9pkho8of1bwxnt5rvgb;
alter table authority add constraint UKj9vkma9pkho8of1bwxnt5rvgb unique (name);
alter table user drop constraint if exists UK6lxhe9wd43lnqsdpb7p2tyydf;
alter table user add constraint UK6lxhe9wd43lnqsdpb7p2tyydf unique (user_name);
alter table users_authorities add constraint FKac1qasdciwqra319h2pa72gh6 foreign key (authority_id) references authority;
alter table users_authorities add constraint FKsy7gt56y8qgp28y3j8ag45glr foreign key (user_id) references user;

CREATE TABLE OAUTH_CLIENT_DETAILS (
  CLIENT_ID VARCHAR(255) PRIMARY KEY,
  RESOURCE_IDS VARCHAR(255),
  CLIENT_SECRET VARCHAR(255),
  SCOPE VARCHAR(255),
  AUTHORIZED_GRANT_TYPES VARCHAR(255),
  WEB_SERVER_REDIRECT_URI VARCHAR(255),
  AUTHORITIES VARCHAR(255),
  ACCESS_TOKEN_VALIDITY INTEGER,
  REFRESH_TOKEN_VALIDITY INTEGER,
  ADDITIONAL_INFORMATION VARCHAR(4096),
  AUTOAPPROVE VARCHAR(255)
);

CREATE TABLE OAUTH_CLIENT_TOKEN (
  TOKEN_ID VARCHAR(255),
  TOKEN VARBINARY,
  AUTHENTICATION_ID VARCHAR(255) PRIMARY KEY,
  USER_NAME VARCHAR(255),
  CLIENT_ID VARCHAR(255)
);

CREATE TABLE OAUTH_ACCESS_TOKEN (
  TOKEN_ID VARCHAR(255),
  TOKEN VARBINARY,
  AUTHENTICATION_ID VARCHAR(255) PRIMARY KEY,
  USER_NAME VARCHAR(255),
  CLIENT_ID VARCHAR(255),
  AUTHENTICATION VARBINARY,
  REFRESH_TOKEN VARCHAR(255)
);

CREATE TABLE OAUTH_REFRESH_TOKEN (
  TOKEN_ID VARCHAR(255),
  TOKEN VARBINARY,
  AUTHENTICATION VARBINARY
);

CREATE TABLE OAUTH_CODE (
  CODE VARCHAR(255),
  AUTHENTICATION VARBINARY
);

CREATE TABLE OAUTH_APPROVALS (
  USERID VARCHAR(255),
  CLIENTID VARCHAR(255),
  SCOPE VARCHAR(255),
  STATUS VARCHAR(10),
  EXPIRESAT TIMESTAMP,
  LASTMODIFIEDAT TIMESTAMP
);